name: Release

on:
  push:
    tags:
      - v*

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: 'x64'
      - name: Cache venv
        uses: actions/cache@v1
        with:
          path: venv
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ubuntu-16.04-poetryenv-${{ hashFiles('poetry.lock') }}
      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install poetry
          poetry install
          python -c "import sys; print(sys.version)"
          pip list
      - name: Poetry Build
        run: |
          . venv/bin/activate
          poetry build

      - name: Upload to Pypi
        env:
          PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          . venv/bin/activate
          poetry publish --username __token__ --password ${PASSWORD}
